apiVersion: v1
kind: Service
metadata:
  name: E Learning-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: E learning
    version: blue # This can be changed to "green" when switching traffic
